/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutHomeRouteImport } from './routes/app/_layout/home'
import { Route as AppLayoutResourcesIndexRouteImport } from './routes/app/_layout/resources/index'
import { Route as AppLayoutGlossaryIndexRouteImport } from './routes/app/_layout/glossary/index'
import { Route as AppLayoutEditorIndexRouteImport } from './routes/app/_layout/editor/index'
import { Route as AppLayoutResourcesIdRouteImport } from './routes/app/_layout/resources/$id'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutHomeRoute = AppLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutResourcesIndexRoute = AppLayoutResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutGlossaryIndexRoute = AppLayoutGlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutEditorIndexRoute = AppLayoutEditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutResourcesIdRoute = AppLayoutResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppLayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/app/home': typeof AppLayoutHomeRoute
  '/app/resources/$id': typeof AppLayoutResourcesIdRoute
  '/app/editor': typeof AppLayoutEditorIndexRoute
  '/app/glossary': typeof AppLayoutGlossaryIndexRoute
  '/app/resources': typeof AppLayoutResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppLayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/app/home': typeof AppLayoutHomeRoute
  '/app/resources/$id': typeof AppLayoutResourcesIdRoute
  '/app/editor': typeof AppLayoutEditorIndexRoute
  '/app/glossary': typeof AppLayoutGlossaryIndexRoute
  '/app/resources': typeof AppLayoutResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/app/_layout/home': typeof AppLayoutHomeRoute
  '/app/_layout/resources/$id': typeof AppLayoutResourcesIdRoute
  '/app/_layout/editor/': typeof AppLayoutEditorIndexRoute
  '/app/_layout/glossary/': typeof AppLayoutGlossaryIndexRoute
  '/app/_layout/resources/': typeof AppLayoutResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/'
    | '/app/home'
    | '/app/resources/$id'
    | '/app/editor'
    | '/app/glossary'
    | '/app/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/'
    | '/app/home'
    | '/app/resources/$id'
    | '/app/editor'
    | '/app/glossary'
    | '/app/resources'
  id:
    | '__root__'
    | '/_layout'
    | '/app'
    | '/app/_layout'
    | '/_layout/'
    | '/app/_layout/home'
    | '/app/_layout/resources/$id'
    | '/app/_layout/editor/'
    | '/app/_layout/glossary/'
    | '/app/_layout/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_layout/home': {
      id: '/app/_layout/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppLayoutHomeRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/resources/': {
      id: '/app/_layout/resources/'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppLayoutResourcesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/glossary/': {
      id: '/app/_layout/glossary/'
      path: '/glossary'
      fullPath: '/app/glossary'
      preLoaderRoute: typeof AppLayoutGlossaryIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/editor/': {
      id: '/app/_layout/editor/'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppLayoutEditorIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/resources/$id': {
      id: '/app/_layout/resources/$id'
      path: '/resources/$id'
      fullPath: '/app/resources/$id'
      preLoaderRoute: typeof AppLayoutResourcesIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutHomeRoute: typeof AppLayoutHomeRoute
  AppLayoutResourcesIdRoute: typeof AppLayoutResourcesIdRoute
  AppLayoutEditorIndexRoute: typeof AppLayoutEditorIndexRoute
  AppLayoutGlossaryIndexRoute: typeof AppLayoutGlossaryIndexRoute
  AppLayoutResourcesIndexRoute: typeof AppLayoutResourcesIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutHomeRoute: AppLayoutHomeRoute,
  AppLayoutResourcesIdRoute: AppLayoutResourcesIdRoute,
  AppLayoutEditorIndexRoute: AppLayoutEditorIndexRoute,
  AppLayoutGlossaryIndexRoute: AppLayoutGlossaryIndexRoute,
  AppLayoutResourcesIndexRoute: AppLayoutResourcesIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
